import { getStrapiURL } from "@/lib/utils";
import qs from "qs";
import "./globals.css";

import type { Metadata } from "next";
import { Abril_Fatface, Metrophobic } from "next/font/google";

import { cn } from "@/lib/utils";

import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { ApiResponse, ApiRootLayout } from "@/types";

const fontSans = Metrophobic({
	variable: "--font-sans",
	weight: "400",
	subsets: ["latin"],
});

const fontHeading = Abril_Fatface({
	variable: "--font-heading",
	weight: "400",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const fetchRootLayout = async () => {
	const { fetchData } = await import("@/lib/fetch");
	const path = "/api/root-layout";
	const baseUrl = getStrapiURL();
	const url = new URL(path, baseUrl);

	const query = qs.stringify({
		populate: {
			nav: {
				populate: "*",
			},
			footer: {
				populate: "*",
			},
		},
	});
	url.search = query;

	const data = await fetchData<ApiResponse<ApiRootLayout>>(url.href);
	return data;
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const data = await fetchRootLayout();

	return (
		<html lang="en">
			<body
				className={cn(
					"flex h-screen flex-col p-5 pt-0 font-sans antialiased",
					fontSans.variable,
					fontHeading.variable,
				)}
			>
				<Header {...data} />
				<main className="content h-full overflow-scroll p-5">
					<div className="h-full overflow-scroll">{children}</div>
				</main>
				<Footer {...data} />
			</body>
		</html>
	);
}
